using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace IronWren.AutoMapper
{
    /// <summary>
    /// Represents a Wren module that was generated by the <see cref="AutoMapper"/>.
    /// </summary>
    internal sealed class Module
    {
        /// <summary>
        /// Gets the string builder used for building the source code.
        /// </summary>
        public StringBuilder Source { get; } = new StringBuilder();

        /// <summary>
        /// Gets whether the module was loaded.
        /// </summary>
        public bool Used { get; private set; }

        public string GetSource()
        {
            Used = true;

            return Source.ToString();
        }
    }
}