using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace IronWren.FullyAutoMapper
{
    /// <summary>
    /// Represents a Wren module that was generated by the <see cref="FullyAutoMapper"/>.
    /// </summary>
    internal sealed class FullyAutoForeignModule
    {
        private readonly Dictionary<string, FullyAutoForeignClass> classes = new Dictionary<string, FullyAutoForeignClass>();

        private readonly StringBuilder source = new StringBuilder();

        /// <summary>
        /// Gets the <see cref="ForeignClass"/>es that are part of the module.
        /// </summary>
        public ReadOnlyDictionary<string, FullyAutoForeignClass> Classes { get; }

        /// <summary>
        /// Gets whether the module's source has been used.
        /// </summary>
        public bool Used { get; private set; }

        public FullyAutoForeignModule()
        {
            Classes = new ReadOnlyDictionary<string, FullyAutoForeignClass>(classes);
        }

        public void Add(Type type)
        {
            var foreignClass = new FullyAutoForeignClass(type);
            classes.Add(foreignClass.Name, foreignClass);

            source.AppendLine(foreignClass.Source);
        }

        public string GetSource()
        {
            Used = true;

            return source.ToString();
        }
    }
}
